import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { SymbolWeight, SymbolViewProps } from "expo-symbols";
import { ComponentProps } from "react";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

type IconMapping = Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>;
type IconSymbolName = keyof typeof MAPPING;

const MAPPING = {
  "house.fill": "home",
  "calendar": "calendar-today",
  "person.2.fill": "people",
  "list.bullet": "list",
  "gearshape.fill": "settings",
  "plus": "add",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "xmark": "close",
  "checkmark": "check",
  "clock.fill": "access-time",
  "phone.fill": "phone",
  "envelope.fill": "email",
  "pencil": "edit",
  "trash.fill": "delete",
  "trash": "delete-outline",
  "magnifyingglass": "search",
  "note.text": "note",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "person.fill": "person",
  "dollarsign.circle.fill": "attach-money",
  "paintpalette.fill": "palette",
  "bell.fill": "notifications",
  "star.fill": "star",
  "arrow.left": "arrow-back",
  "mappin": "place",
  "mappin.and.ellipse": "place",
  "mappin.circle.fill": "place",
  "globe": "language",
  "message.fill": "message",
  "person.crop.circle.badge.plus": "person-add",
  "chart.bar.fill": "bar-chart",
  "chart.pie.fill": "pie-chart",
  "arrow.up.right": "trending-up",
  "crown.fill": "emoji-events",
  "circle.fill": "circle",
  "checkmark.circle": "check-circle-outline",
  "checkmark.circle.fill": "check-circle",
  "xmark.circle.fill": "cancel",
  "questionmark.circle.fill": "help",
  "moon.fill": "dark-mode",
  "sun.max.fill": "light-mode",
  "circle.lefthalf.filled": "contrast",
  "photo": "image",
  "doc.text.fill": "description",
  "square.and.arrow.up": "share",
  "square.and.arrow.up.fill": "file-upload",
  "arrow.down.doc.fill": "file-download",
  "calendar.badge.clock": "event",
  "tag.fill": "local-offer",
  "gift.fill": "card-giftcard",
  "birthday.cake": "cake",
  "birthday.cake.fill": "cake",
  "percent": "percent",
  "qrcode": "qr-code",
  "link": "link",
  "calendar.badge.plus": "event-available",
  "calendar.badge.minus": "event-busy",
  "clock.badge.checkmark.fill": "schedule",
  "power": "power-settings-new",
  "info.circle.fill": "info",
  "arrow.clockwise": "refresh",
  "lock.fill": "lock",
  "lock.open.fill": "lock-open",
  "faceid": "face",
  "touchid": "fingerprint",
  "copy": "content-copy",
  "bag.fill": "shopping-bag",
  "shippingbox.fill": "inventory",
  "person.badge.plus": "person-add",
  "person.3.fill": "groups",
  "briefcase.fill": "work",
  "paintbrush.fill": "brush",
  "building.2.fill": "business",
  "exclamationmark.triangle.fill": "warning",
  "arrow.right.square.fill": "logout",
  "arrow.up.right.square": "open-in-new",
  "location.fill": "location-on",
  "building.fill": "apartment",
  "gear": "settings",
  "doc.on.doc.fill": "file-copy",
  "rectangle.stack.fill": "layers",
  "chevron.down": "expand-more",
  "calendar.badge.checkmark": "event-available",
  "arrow.down.right": "trending-down",
  "arrow.down.to.line": "save-alt",
  "photo.badge.plus": "add-photo-alternate",
  "photo.fill": "image",
  "creditcard.fill": "credit-card",
  "creditcard": "credit-card",
  "banknote.fill": "payments",
  "arrow.up.arrow.down": "swap-vert",
  "target": "gps-fixed",
  "flag.fill": "flag",
  "trophy.fill": "emoji-events",
  "ticket.fill": "confirmation-number",
  "ticket": "confirmation-number",
  "clock.badge.fill": "alarm-on",
  "bell.badge.fill": "notification-important",
  "wand.and.stars": "auto-fix-high",
  "sparkles": "auto-awesome",
  "chart.line.uptrend.xyaxis": "show-chart",
  "person.badge.clock.fill": "pending-actions",
} as unknown as IconMapping;

export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
